{"name": "Login with invalid mobile number -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x55d87cd47303 <unknown>\n#1 0x55d87cb1bd37 <unknown>\n#2 0x55d87cb48a54 <unknown>\n#3 0x55d87cb4380e <unknown>\n#4 0x55d87cb40330 <unknown>\n#5 0x55d87cb814a6 <unknown>\n#6 0x55d87cb78753 <unknown>\n#7 0x55d87cb4ba14 <unknown>\n#8 0x55d87cb4cb7e <unknown>\n#9 0x55d87cd9632e <unknown>\n#10 0x55d87cd99c0e <unknown>\n#11 0x55d87cd7c610 <unknown>\n#12 0x55d87cd9ac23 <unknown>\n#13 0x55d87cd6e545 <unknown>\n#14 0x55d87cdbb6a8 <unknown>\n#15 0x55d87cdbb836 <unknown>\n#16 0x55d87cdd6d13 <unknown>\n#17 0x7fa56229bfd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x55d87cd47303 <unknown>\n#1 0x55d87cb1bd37 <unknown>\n#2 0x55d87cb48a54 <unknown>\n#3 0x55d87cb4380e <unknown>\n#4 0x55d87cb40330 <unknown>\n#5 0x55d87cb814a6 <unknown>\n#6 0x55d87cb78753 <unknown>\n#7 0x55d87cb4ba14 <unknown>\n#8 0x55d87cb4cb7e <unknown>\n#9 0x55d87cd9632e <unknown>\n#10 0x55d87cd99c0e <unknown>\n#11 0x55d87cd7c610 <unknown>\n#12 0x55d87cd9ac23 <unknown>\n#13 0x55d87cd6e545 <unknown>\n#14 0x55d87cdbb6a8 <unknown>\n#15 0x55d87cdbb836 <unknown>\n#16 0x55d87cdd6d13 <unknown>\n#17 0x7fa56229bfd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678338689299, "stop": 1678338693382}, {"name": "When Open the URL https://www.abhibus.com/ website", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}, {"name": "Then Click on the Login link", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}, {"name": "And Enter an invalid mobile number \"00123423\"", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}, {"name": "And Click the Login or Signup button", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}, {"name": "And Error message is displayed when mobile number is invalid", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}, {"name": "Then Close the browser", "status": "skipped", "start": 1678338693383, "stop": 1678338693383}], "parameters": [{"name": "mobilenumber", "value": "00123423"}], "start": 1678338689298, "stop": 1678338693383, "uuid": "ccd70305-f069-4bc7-b3a6-b1d01e5bc540", "historyId": "8ecddf5dff878c38785eb739ccb30278", "fullName": "validate the login feature: Login with invalid mobile number", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "invalid_login"}, {"name": "feature", "value": "validate the login feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}