{"name": "Login with invalid mobile number -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x55df9f240303 <unknown>\n#1 0x55df9f014d37 <unknown>\n#2 0x55df9f041a54 <unknown>\n#3 0x55df9f03c80e <unknown>\n#4 0x55df9f039330 <unknown>\n#5 0x55df9f07a4a6 <unknown>\n#6 0x55df9f071753 <unknown>\n#7 0x55df9f044a14 <unknown>\n#8 0x55df9f045b7e <unknown>\n#9 0x55df9f28f32e <unknown>\n#10 0x55df9f292c0e <unknown>\n#11 0x55df9f275610 <unknown>\n#12 0x55df9f293c23 <unknown>\n#13 0x55df9f267545 <unknown>\n#14 0x55df9f2b46a8 <unknown>\n#15 0x55df9f2b4836 <unknown>\n#16 0x55df9f2cfd13 <unknown>\n#17 0x7f4cde377fd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x55df9f240303 <unknown>\n#1 0x55df9f014d37 <unknown>\n#2 0x55df9f041a54 <unknown>\n#3 0x55df9f03c80e <unknown>\n#4 0x55df9f039330 <unknown>\n#5 0x55df9f07a4a6 <unknown>\n#6 0x55df9f071753 <unknown>\n#7 0x55df9f044a14 <unknown>\n#8 0x55df9f045b7e <unknown>\n#9 0x55df9f28f32e <unknown>\n#10 0x55df9f292c0e <unknown>\n#11 0x55df9f275610 <unknown>\n#12 0x55df9f293c23 <unknown>\n#13 0x55df9f267545 <unknown>\n#14 0x55df9f2b46a8 <unknown>\n#15 0x55df9f2b4836 <unknown>\n#16 0x55df9f2cfd13 <unknown>\n#17 0x7f4cde377fd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678338693386, "stop": 1678338697109}, {"name": "When Open the URL https://www.abhibus.com/ website", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}, {"name": "Then Click on the Login link", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}, {"name": "And Enter an invalid mobile number \"901068\"", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}, {"name": "And Click the Login or Signup button", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}, {"name": "And Error message is displayed when mobile number is invalid", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}, {"name": "Then Close the browser", "status": "skipped", "start": 1678338697110, "stop": 1678338697110}], "parameters": [{"name": "mobilenumber", "value": "901068"}], "start": 1678338693384, "stop": 1678338697110, "uuid": "f7feb69b-c666-4687-9138-97e3dd4dcaca", "historyId": "274181b80f90603c2abc667f3a2f3b1d", "fullName": "validate the login feature: Login with invalid mobile number", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "invalid_login"}, {"name": "feature", "value": "validate the login feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}